### ISSUE TITLE
invite me

### ISSUE THREAD

**Issue by ghost** [byronbytes/byronbytes#1]
invite me
to mono
@byronbytes

**Comment by ghost** [comment]
@byronbytes

**Comment by ghost** [comment]
also invite @patrik1123456

**Comment by ghost** [comment]
and invite @Sparmage too

**Comment by byronbytes** [comment]
today is field day

**Comment by patrik1123456** [comment]
> 

nigga i got a email telling me about this

**Comment by byronbytes** [comment]
1. sometimes when you push changes, it breaks another thing. please make sure to pass by all features by me (i know that sounds rude but its for stability)
2. Do NOT skid. this client was already leaked before.
3. dont overwork yourself on this client, i only do this as a hobby and i dont have intentions of being in the community.

**Comment by patrik1123456** [comment]
ok daddy

**Comment by patrik1123456** [comment]
can i get dev now
